# Generated by Django 3.0.4 on 2020-04-06 20:31

from django.db import migrations, models
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.profile_image_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
