# Generated by Django 3.0.4 on 2020-03-24 16:58

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.utils.profile_image_directory_path),
        ),
    ]
