# Generated by Django 3.0.4 on 2020-03-24 17:23

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_added_profile_image_to_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.profile_image_directory_path),
        ),
    ]
