# Generated by Django 3.0.4 on 2020-04-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_searchprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchprofiles',
            name='min_bedrooms',
        ),
        migrations.RemoveField(
            model_name='searchprofiles',
            name='min_rooms',
        ),
        migrations.AddField(
            model_name='searchprofiles',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='searchprofiles',
            name='rooms',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='max_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Maximum price'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='min_price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Minimum price'),
        ),
    ]
