# Generated by Django 3.0.4 on 2020-04-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200410_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchprofiles',
            unique_together={('user', 'title')},
        ),
    ]
