# Generated by Django 3.0.4 on 2020-04-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_added_is_active_status_to_search_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchprofiles',
            options={'verbose_name_plural': 'Search profiles'},
        ),
    ]
