# Generated by Django 3.0.4 on 2020-05-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200428_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchProfiles',
        ),
    ]
