# Generated by Django 3.0.4 on 2020-05-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_bookmarks_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'verbose_name_plural': 'Bookmarks'},
        ),
    ]
