# Generated by Django 3.0.4 on 2020-03-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_listing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofiles',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For rent'), ('buy', 'For buy')], default='rent', help_text='Designates the type of search profile: rent or sell', max_length=10, verbose_name='Listing type'),
        ),
    ]
