# Generated by Django 3.0.4 on 2020-03-25 15:43

from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_added_listing_type_to_searchprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=users.utils.listing_image_directory_path)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
