# Generated by Django 3.0.4 on 2020-03-25 18:08

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_added_Image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(default=1, upload_to=users.utils.listing_image_directory_path),
            preserve_default=False,
        ),
    ]
