# Generated by Django 3.0.4 on 2020-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_added_slug_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchProfiles',
        ),
    ]
