# Generated by Django 3.0.4 on 2020-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_delete_searchprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('house', 'A house'), ('apartment', 'An apartment')], default='house', max_length=10, verbose_name='Type of home'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For rent'), ('sell', 'For sell')], default='rent', max_length=10, verbose_name='Listing type'),
        ),
    ]
