# Generated by Django 3.0.4 on 2020-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20200411_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='heating',
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.CharField(choices=[('central', 'Central Heating'), ('gas', 'Gas'), ('ac', 'AC'), ('other', 'Other...'), ('none', 'None')], default='Gas', max_length=50),
        ),
        migrations.DeleteModel(
            name='HeatingChoices',
        ),
    ]
