# Generated by Django 3.0.4 on 2020-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20200412_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='heating',
            field=models.CharField(choices=[('central', 'Central heating'), ('solar', 'Solar energy'), ('electricity', 'Electricity'), ('gas', 'Gas'), ('wood', 'Wood stove'), ('other', 'Other...'), ('none', 'None')], default='Gas', max_length=50),
        ),
    ]
