# Generated by Django 3.0.4 on 2020-05-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200428_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cover_image',
        ),
    ]
