# Generated by Django 3.0.4 on 2020-05-22 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_cover_image_as_field_from_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('house', 'A house'), ('apartment', 'An apartment')], default='apartment', max_length=10, verbose_name='Type of home'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='Zip code must be in format 1234AB', regex='.*?')], verbose_name='Zip-code'),
        ),
    ]
