# Generated by Django 3.0.4 on 2020-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200522_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('', 'Select home type'), ('house', 'A house'), ('apartment', 'An apartment')], default='apartment', max_length=10, verbose_name='Type of home'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior',
            field=models.CharField(choices=[('', 'Select interior'), ('unspecified', 'Not specified'), ('furnished', 'Fully furnished'), ('unfurnished', 'Non furnished'), ('upholstered', 'Semi furnished')], default='unspecified', max_length=255),
        ),
    ]
