# Generated by Django 3.0.4 on 2020-05-27 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20200526_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='construction_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Construction Year'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], default='apartment', max_length=10, verbose_name='Type of home'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interior',
            field=models.CharField(choices=[('unfurnished', 'Non furnished'), ('upholstered', 'Semi furnished'), ('furnished', 'Fully furnished'), ('unspecified', 'Not specified')], default='unfurnished', max_length=255),
        ),
    ]
