# Generated by Django 3.0.4 on 2020-05-27 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0014_add_construction_year_amend_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of rooms')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of bedrooms')),
                ('min_price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Minimum price')),
                ('max_price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Maximum price')),
                ('home_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Home type')),
                ('listing_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='Listing type')),
                ('interior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Interior')),
                ('frequency', models.CharField(max_length=50, verbose_name='Update frequency')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchprofiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search profiles',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
