# Generated by Django 3.0.4 on 2020-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchprofiles', '0001_search_profiles_initial_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprofiles',
            name='home_type',
            field=models.CharField(choices=[('', 'Select home type'), ('house', 'A house'), ('apartment', 'An apartment')], max_length=20, null=True, verbose_name='Home type'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='frequency',
            field=models.CharField(choices=[('', 'Select frequency'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('instant', 'Instantly')], default='weekly', max_length=255, verbose_name='Update frequency'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='interior',
            field=models.CharField(choices=[('', 'Select interior'), ('unspecified', 'Not specified'), ('furnished', 'Fully furnished'), ('unfurnished', 'Non furnished'), ('upholstered', 'Semi furnished')], max_length=15),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='listing_type',
            field=models.CharField(choices=[('', 'Select type'), ('rent', 'For rent'), ('buy', 'For buy')], max_length=10, verbose_name='Listing type'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='rooms',
            field=models.PositiveSmallIntegerField(verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='searchprofiles',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
